import { Routes } from '@angular/router';
import { HomeComponent } from './pages/home/home.component';
import { BillSplitComponent } from './pages/bill-split/bill-split.component';
import { ImgCompressComponent } from './pages/img-compress/img-compress.component';
import { KidsMathUtilComponent } from './pages/kids-math-util/kids-math-util.component';
import { PdfToWordComponent } from './pages/pdf-to-word/pdf-to-word.component';
import { PdfToWordAltComponent } from './pages/pdf-to-word-alt/pdf-to-word-alt.component';
import { FlightItineraryComponent } from './pages/flight-itinerary/flight-itinerary.component';
import { AboutUsComponent } from './pages/about-us/about-us.component';
import { ContactUsComponent } from './pages/contact-us/contact-us.component';
import { TermsAndConditionComponent } from './pages/terms-and-condition/terms-and-condition.component';
import { PrivacyPolicyComponent } from './pages/privacy-policy/privacy-policy.component';
import { ThankYouComponent } from './pages/thank-you/thank-you.component';
import { PdfMergerComponent } from './pages/pdf-merge/pdf-merge.component';
import { PdfUnlockComponent } from './pages/pdf-unlock/pdf-unlock.component';
import { PdfLockComponent } from './pages/pdf-lock/pdf-lock.component';
import { ImageToWordComponent } from './pages/image-to-word/image-to-word.component';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'bill-split', component: BillSplitComponent },
  { path: 'img-compress', component: ImgCompressComponent },
  { path: 'kids-math-util', component: KidsMathUtilComponent },
  { path: 'pdf-to-word', component: PdfToWordComponent },
  { path: 'pdf-to-word-alt', component: PdfToWordAltComponent },
  { path: 'flight-itinerary', component: FlightItineraryComponent },
  { path: 'about-us', component: AboutUsComponent },
  { path: 'contact-us', component: ContactUsComponent },
  { path: 'terms-conditions', component: TermsAndConditionComponent },
  { path: 'privacy-policy', component: PrivacyPolicyComponent },
  { path: 'thank-you', component: ThankYouComponent },
  { path: 'pdf-merge', component: PdfMergerComponent },
  { path: 'pdf-unlock', component: PdfUnlockComponent },
  { path: 'pdf-lock', component: PdfLockComponent },
  { path: 'image-to-word', component: ImageToWordComponent },
  { path: '**', redirectTo: '' }
];
